### ISSUE TITLE
Need to indicate that more sensors are supported in the documentation

### ISSUE THREAD

**Issue by RichieRich69** [ESPresense/ESPresense.github.io#15]
It's currently hard to tell that the following sensors are also supported by ESPresense when you look at the documentation:
* Temperature (DHT11, DHT22)
* Ambient Light (BH1750, TSL2561)
* Weather Sensor (BME280)
* Weight Sensor (HX711)

Addition it to the documentation will increase the overall popularity of the firmware, since several people end up using two ESP32 to accomplish something that could have been done with just ESPresense.

**Comment by DTTerastar** [comment]
Thank you for helping w/ the documentation.  I appreciate it!
