### ISSUE TITLE
Feature Request: add support for mmWave Radar

### ISSUE THREAD

**Issue by EvisHome** [ESPresense/ESPresense.github.io#21]
Could you add support for mmWare Radar

e.g. https://www.dfrobot.com/product-2282.html

Also fits in my ESPresense enclosure (with EPS32 + PIR)
https://www.tinkercad.com/things/5CkzC6C2VLl-esp32-pir-case-with-wall-mount
https://www.thingiverse.com/thing:5353636

![image](https://user-images.githubusercontent.com/98347572/172227119-c18aea65-e8d4-48a1-835d-0c067b4365d4.png)
![image](https://user-images.githubusercontent.com/98347572/172227171-7fc2d2ca-da29-45a8-921c-88a022da3cb6.png)
![image](https://user-images.githubusercontent.com/98347572/172227301-c9bc2236-add5-4e1f-86a4-476f87783b71.png)

**Comment by DTTerastar** [comment]
There is an simple out signal w/ those, you can hook that to a pin and use that pin for radar and it should work.

**Comment by EvisHome** [comment]
I noticed that I posted this request into wrong place, can be closed in here
