### ISSUE TITLE
Link does not direct to ESP32 Board

### ISSUE THREAD

**Issue by lloydatron** [ESPresense/ESPresense.github.io#23]
Unfortunately, I didn't double-check, trusted this link and purchased ESP8266 ESP-12F, not ESP32s. I think this link is incorrect.

https://amzn.to/3tlkK8D

https://espresense.com/base-stations
[D1 Mini ESP32](https://amzn.to/3tlkK8D)

**Comment by DTTerastar** [comment]
I see it link to an ESP32.  Is there a better board to link to?  I wish m5atoms were on amazon (there are a few scalpers, but no real links that i've found)

**Comment by lloydatron** [comment]
Thanks for checking @DTTerastar, I tried the link again and it sends me to the following ESP-12F which is not compatible + doesn't have Bluetooth. Do you see the following description and ASIN: B074Q2WM1Y on that link?
AZDelivery NodeMCU WiFi Lolin V3 ESP8266 ESP-12F Internet Development Board Module (32mbit) Flash Memory Chip Series Port Adapter with CH340 compatible with Arduino Including E-Book! (Pack of 3)

I'm just trying to avoid anyone else falling into the trap I did.

I ordered this ESP32 the other day and it's running Espresence all good, this link. SP-Cow ESP32S ESP32 Development Board 2.4GHz Dual-Mode WiFi+ Bluetooth Dual Cores Microcontroller Processor, Antenna Module with RF AMP Filter AP STA IDE Ultra Low Power (1 Pc) https://amzn.eu/d/aGTmZhl

Cheers

**Comment by lloydatron** [comment]
Sorry I didn't mean to close

**Comment by DTTerastar** [comment]
Ok Amazon has a thing called "one link" and it was set to redirect to a simiar link when used internationally.  I've set it to exact.  Can you retry it now?  It should just stay on the US one and maybe help you get to one on your amazon store?

**Comment by lloydatron** [comment]
Nice one for sorting this @DTTerastar it does direct me to the US store which I guess is ok as it looks like the correct board. Just FYI it looks like you might have broken the formatting on the site layout (attached), nice one for the comment about checking its an ESP32
![espresense_com:base-stations](https://user-images.githubusercontent.com/63158792/174758974-025bb44a-3a89-405e-9de3-0edf26fe8c19.png)
!

**Comment by DTTerastar** [comment]
Yup, fixed:
![image](https://user-images.githubusercontent.com/1491145/175572916-5a9a3201-2e48-4a1b-b0dd-bcc21968494e.png)
