### ISSUE TITLE
Home Assistant Android Companion BLE Transmitter

### ISSUE THREAD

**Issue by sourbrambles** [ESPresense/ESPresense.github.io#3]
Suggestion to add alternative android BLE transmitter option. HA Companion app allows you to transmit a beacon e.g.

> A BLE Transmitter sensor allows your device to transmit a BLE iBeacon. This is useful in conjunction with projects like roomassistant and esp32-mqtt-room to allow room level tracking. The current transmitting ID (UUID-Major-Minor) is reported as an attribute that can be copied for use with these systems.
>
>CAUTION
This sensor can impact battery life, particularly if used wih Transmit Power set to High. The iBeacon is transmitted every second (low latency to save battery, but sufficient for room presence).
>
>Settings are available to change the UUID, Major and Minor masks. These can be used to change the overall identifier, as well as to allow groups, e.g. family phone devices can have particular Major value which can be whitelisted in apps like roomassistant. These settings are validated: UUID should be the standard format, Major and Minor need to be within 0 and 65535. There are also settings to change the Transmit power (between Ultra Low, Low, Medium and High) as well as as toggle to allow this sensor to be turned on when the Enable all sensors toggle is activated. This is set to false, to prevent this sensor draining battery unnecessarily.
>
>A Transmit setting toggle will start or stop the BLE transmissions - this setting is also toggled via the notification command that can turn the services on and off.

Source: https://companion.home-assistant.io/docs/core/sensors/#bluetooth-sensors

I've only been using ESPresense for a day and the HA BLE Transmit for half a day but so far everything is working well. 

I'm not familiar with pull requests or git stuff but happy to try and make an amendment to the https://github.com/ESPresense/ESPresense.github.io/blob/master/apps.md and do a pull request or happy to leave this as a suggestion.

**Comment by DTTerastar** [comment]
I've been trying to figure out where those iBeacons we coming from!  I even looked through those HA Companion docs to find it!

Yes, please hit the edit button on the docs and add that!
