### ISSUE TITLE
Bluetooth available with ESP

### ISSUE THREAD

**Issue by Merangle** [ESPresense/ESPresense.github.io#42]
hello 

HA has improved BT support and in order to improve the range of BT within the house has developed the concept of BT proxies 
[](https://esphome.github.io/bluetooth-proxies/)
I don't know if BT is available now, but do you think it could make sense to allow ESP32 to become BT proxies ? 
Thanks for your help

**Comment by DTTerastar** [comment]
This is where we are talking about that idea: https://github.com/ESPresense/ESPresense/issues/652
