### ISSUE TITLE
Report Working Beacon Device

### ISSUE THREAD

**Issue by 86lava** [ESPresense/ESPresense.github.io#44]
The [Innway Slim Rechargeable Tracking Card](https://www.amazon.com/Innway-Card-Rechargeable-Bluetooth-Backpack/dp/B07MYZWM3B) works right out of the box as it transmits iBeacon messages.  Sorry if this is an unacceptable way to report this.  Project forking and bitly accounts are way too complicated.  Thanks for this terrific project.

**Comment by DTTerastar** [comment]
PRs would be a nicer way of doing this!

**Comment by 86lava** [comment]
Added to working beacons list on Mar 22, 2023
