### ISSUE TITLE
Add device to known beacons

### ISSUE THREAD

**Issue by kryptonitecb3** [ESPresense/ESPresense.github.io#48]
I know this isn't the correct place but I couldn't find a good way to submit known working devices. When I selected "edit this page on github" it leads me to a page saying I need to fork the repository.

Cat-Tailer devices work without issue. They use the ibeacon protocol and instantly showed up in espresence as ibeacon devices. They also used fixed mac addresses, worked immediately out of the box, and come in a waterproof housing. I got two of these over a year ago and have had no issues with them.
https://www.amazon.com/stores/CAT+TAILER/page/411D977A-E1F9-408C-9B5D-387B676700B2?ref_=ast_bln

Example of devices:
mac address - e4:81:dc:42:5f:cc
ibeacon broadcast - ab4e0840e2ea11e4ab0d0002a5d5c51b-38807-45270
espresence device id - iBeacon:ab4e0840-e2ea-11e4-ab0d-0002a5d5c51b-38807-45270

mac address - d3:36:3e:1a:55:92
ibeacon broadcast - ab4e0840e2ea11e4ab0d0002a5d5c51b-9527-41941
espresence device id - iBeacon:ab4e0840-e2ea-11e4-ab0d-0002a5d5c51b-9527-41940

**Comment by DTTerastar** [comment]
PRs would be a nicer way of doing this!
