### ISSUE TITLE
Add Galaxy Watch 5 Pro to known working lists

### ISSUE THREAD

**Issue by somejavadev** [ESPresense/ESPresense.github.io#56]
Hi,

The Samsung galaxy watch 5 pro works when used with home assistant and the home assistant companion app. For this to work you need to install the companion app for your wearable and enable the Bluetooth tracker sensor which creates an iBeacon.  
  
My guess here is that this might work for other Android wearables depending on the app compatibility with the watch.

One thing I have noticed is the transmit rssi@1m seems to be slightly off and cannot be adjusted at this time.

**Comment by labaland** [comment]
iI just went here to also report that my gf's watch "SAMSUNG Galaxy Watch 5 (40mm) LTE" works perfectly too :) 
But i have not enabled bluetooth in ha app on her watch!

&

My Xiaomi Mi Band 6 works too. No special settings what i have done

**Comment by DTTerastar** [comment]
PRs would be a nicer way of doing this!
