### ISSUE TITLE
Feature Request: Add links for enclosures.

### ISSUE THREAD

**Issue by rrosson** [ESPresense/ESPresense.github.io#6]
It would be cool to add a link(s) in documentation from the community  of some various enclosures that have been 3dprinted (hopefully with style files) to house the boards with the various configurations.

**Comment by DTTerastar** [comment]
Yes, agreed, anybody know of any?

**Comment by RichieRich69** [comment]
@DTTerastar I've spent this week designing a few on Fusion 360. On which page would it be nice to add those links?

**Comment by DTTerastar** [comment]
https://github.com/ESPresense/ESPresense.github.io/blob/master/hardware/enclosures.md

**Comment by EvisHome** [comment]
I have some, free to use

https://www.thingiverse.com/thing:5353636

https://www.tinkercad.com/things/5CkzC6C2VLl-esp32-pir-case-with-wall-mount

**Comment by DTTerastar** [comment]
Added those: https://github.com/ESPresense/ESPresense.github.io/blob/master/hardware/enclosures.md
